use_frameworks!

platform :ios, '8.0'

target 'ZYShoppingComponents_Example' do
  pod 'ZYShoppingComponents', :path => '../'

  target 'ZYShoppingComponents_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
